// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package module.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Module module
	public static void act_Close_Page_1(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Module.Act_Close_Page_1").withParams(params).execute(context);
	}
	public static void act_Nav_Tab1(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Module.Act_Nav_Tab1").withParams(params).execute(context);
	}
	public static void act_Nav_Tab2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Module.Act_Nav_Tab2").withParams(params).execute(context);
	}
	public static void act_Nav_TabNormal(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Module.Act_Nav_TabNormal").withParams(params).execute(context);
	}
	public static void nav_TabRouter_With_Tab2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Module.Nav_TabRouter_With_Tab2").withParams(params).execute(context);
	}
}
